# Generated by Django 4.2.22 on 2026-05-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_role',
            field=models.CharField(choices=[('player', 'Gracz'), ('game_master', 'Mistrz Gry')], default='player', max_length=24),
        ),
    ]
