RULESETS = [
    {
        'slug': 'dnd5e',
        'name': 'Dungeons & Dragons 5E',
        'family': 'd20',
        'primary_die': 'd20',
        'theme': 'heroic-fantasy',
        'dice': ['d4', 'd6', 'd8', 'd10', 'd12', 'd20', 'd100'],
        'terms': {'character_class': 'Class', 'ancestry': 'Ancestry', 'level': 'Level'},
        'sort_order': 10,
    },
    {
        'slug': 'call-of-cthulhu',
        'name': 'Call of Cthulhu',
        'family': 'percentile',
        'primary_die': 'd100',
        'theme': 'investigation-horror',
        'dice': ['d100', 'd10', 'd6'],
        'terms': {'character': 'Investigator', 'profession': 'Occupation', 'sanity': 'Sanity'},
        'sort_order': 20,
    },
    {
        'slug': 'year-zero',
        'name': 'Year Zero / Tajemnice Pętli i Powodzi',
        'family': 'dice-pool-d6',
        'primary_die': 'd6 pool',
        'theme': 'retro-science',
        'dice': ['d6'],
        'terms': {'character': 'Kid', 'attribute': 'Attribute', 'condition': 'Condition'},
        'sort_order': 30,
    },
    {
        'slug': 'warhammer-4e',
        'name': 'Warhammer Fantasy Roleplay 4E',
        'family': 'percentile',
        'primary_die': 'd100',
        'theme': 'grim-fantasy',
        'dice': ['d100', 'd10', 'd6'],
        'terms': {'career': 'Career', 'wounds': 'Wounds', 'advantage': 'Advantage'},
        'sort_order': 40,
    },
    {
        'slug': 'vampire-v5',
        'name': 'Vampire: The Masquerade 5E',
        'family': 'dice-pool-d10',
        'primary_die': 'd10 pool',
        'theme': 'urban-noir',
        'dice': ['d10'],
        'terms': {'clan': 'Clan', 'hunger': 'Hunger', 'humanity': 'Humanity'},
        'sort_order': 50,
    },
    {
        'slug': 'kult',
        'name': 'Kult: Divinity Lost',
        'family': '2d10',
        'primary_die': '2d10',
        'theme': 'industrial-horror',
        'dice': ['d10'],
        'terms': {'archetype': 'Archetype', 'stability': 'Stability', 'relation': 'Relation'},
        'sort_order': 60,
    },
]
