# Generated by Django 4.2.22 on 2026-05-16 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='context',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='campaignmember',
            name='role',
            field=models.CharField(choices=[('player', 'Gracz'), ('game_master', 'Mistrz Gry')], default='player', max_length=24),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('note', 'Notatka'), ('session', 'Sesja'), ('event', 'Wydarzenie'), ('reward', 'Nagroda')], default='note', max_length=24)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='rpg.campaign')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='rpg.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wpis dziennika',
                'verbose_name_plural': 'wpisy dziennika',
                'ordering': ['-created_at'],
            },
        ),
    ]
